### ISSUE TITLE
why did watcdog ban me :(( ? !

### ISSUE THREAD

**Issue by rares1337** [Invecz/caterpillow#3]
sorry i have 3 iq and i dont cnow why haipixel banned me :((
i jast wanna play quakecraft with this mod :((

i am super dumb dumb

**Comment by Paddyk45** [comment]
hmm why did they ban you? maybe This mod is cheating and eatchdog detechted it :P

**Comment by Paddyk45** [comment]
i know its just a joke issue :P

**Comment by rares1337** [comment]
yes lmfao

**Comment by mekb-turtle** [comment]
@Invecz pls respond **!**
